samples: combined_samples.tsv

BWT2_IDX: /GRCh38_primary_assembly_mod

### Post processing parameters
###Bed file for no_of_reads_per_region and R_analysis
###

user_bed_dir: input_bed

GeneMatching:
    TSSDist: 100 ##Any integer for TSSDist
    
##JaccardSim_QueryBed_To_TCGAPeaks specific
JaccardSim:
    top_SamNum: 5 ##Any integer for top sample number
    sample_name: TCGA-2G-AAFM ##Any name to be given for sample
    tissue_name: GBM ##Tissue to be matched

vGENCODE: 34
